### ISSUE TITLE
Organize file system to be more organized for multiple pages

### ISSUE THREAD

**Issue by farhan-mohammed** [InnovationTank/innovationtank.ca#3]
Whoever's doing this can plan their system and we will implement it.

What I want:

/src
---- /components 
----/pages
--------/earsavers
--------/ages
----/media
--------/earsavers
--------/ages
-------/folder for whatever you think works

I also want a wrapper component where we can fill the contents with each specific blog, this would work using 

```jsx
{this.props.children}
```

Basically the point of this we have a component such as 
```jsx
<div>
   <Header />
    <div classname="body">
         {this.props.children}
     </div>
    <Footer />
</div>
```
and we replace the children each time

**Comment by s6eskand** [comment]
For wrapper component, do we have a design of how that would look as of right now? Or could we atleast bring that up with design team.

**Comment by s6eskand** [comment]
Also, would my views directory with each view being its own component be a solution to resolve this issue?

**Comment by farhan-mohammed** [comment]
Oh I see what you mean, yeah I feel like the router/view component is basically wrapped by the other components and we change the components based on the routes, so all good for now.
